"""
Alert model.

Stores every intrusion detection event generated by the IDS.
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, Float, Integer, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from database.base import Base


class Alert(Base):
    __tablename__ = "alerts"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )

    source_ip: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        index=True,
    )

    destination_ip: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        index=True,
    )

    source_port: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
    )

    destination_port: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
    )

    protocol: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
    )

    attack_type: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        index=True,
    )

    confidence: Mapped[float] = mapped_column(
        Float,
        nullable=False,
    )

    severity: Mapped[str] = mapped_column(
        String(20),
        default="Medium",
    )

    risk_score: Mapped[int] = mapped_column(
        Integer,
        default=50,
    )

    status: Mapped[str] = mapped_column(
        String(30),
        default="Open",
    )

    mitre_attack: Mapped[str | None] = mapped_column(
        String(100),
        nullable=True,
    )

    llm_summary: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    # Relationships

    predictions = relationship(
        "Prediction",
        back_populates="alert",
    )

    incidents = relationship(
        "Incident",
        back_populates="alert",
        cascade="all, delete-orphan",
    )